<a href="https://colab.research.google.com/github/Aayush07Patil/Pytorch-Tutorial/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape Tensor
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# Reshape Without knowing values with -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [8]:
#views

my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
my_torch4 = my_torch3.view(3,5)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [10]:
# View and reshape update on change in original tensor

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch5[1]= 1423
my_torch5

tensor([   0, 1423,    2,    3,    4,    5,    6,    7,    8,    9])

In [13]:
my_torch6

tensor([[   0, 1423,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [14]:
#Slicers

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#Grab a specfic item
my_torch7[6]

tensor(6)

In [16]:
#Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [18]:
my_torch8[:,0]

tensor([0, 2, 4, 6, 8])

In [19]:
# maintain the column shape
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [20]:
my_torch8[:,0:]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])